T = thingSpeakRead(1552033, ...
    Fields=[1], ...
    NumPoints=620, ...
    ReadKey='AD8ZB04MFD6HIYI8', ...
    OutputFormat='table');
Tdat = T(:, {'cmvsData'});
Tstr = rowfun(@string, Tdat);
Tarr = Tstr{:,:};
Cell = arrayfun(@(x) uint32(str2num(x)),Tarr,'uniform',0); %#ok<ST2NM> 
Mat = cell2mat(Cell);
Mat